// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCEJgfSqSgDoxNlzu0hGhu2nBWmVWtviY',
    appId: '1:883016729268:web:16a0c78b7731c90dd90de1',
    messagingSenderId: '883016729268',
    projectId: 'allycall',
    authDomain: 'allycall.firebaseapp.com',
    storageBucket: 'allycall.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYpU8NhusEZyHlqx49kSDbNSt03jAAFOQ',
    appId: '1:883016729268:android:3d1f36312d60e0c5d90de1',
    messagingSenderId: '883016729268',
    projectId: 'allycall',
    storageBucket: 'allycall.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn7XeFnskP9cc95Lh1zM5IktL0RBcfuQg',
    appId: '1:883016729268:ios:637120bffc41d4bcd90de1',
    messagingSenderId: '883016729268',
    projectId: 'allycall',
    storageBucket: 'allycall.firebasestorage.app',
    androidClientId: '883016729268-lkn8j4s2vhtm63781iijvpfuufg0ft4n.apps.googleusercontent.com',
    iosClientId: '883016729268-te1gqudtj6v1lpm4v4qjn3641s9fo1nl.apps.googleusercontent.com',
    iosBundleId: 'com.example.allycall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn7XeFnskP9cc95Lh1zM5IktL0RBcfuQg',
    appId: '1:883016729268:ios:637120bffc41d4bcd90de1',
    messagingSenderId: '883016729268',
    projectId: 'allycall',
    storageBucket: 'allycall.firebasestorage.app',
    androidClientId: '883016729268-lkn8j4s2vhtm63781iijvpfuufg0ft4n.apps.googleusercontent.com',
    iosClientId: '883016729268-te1gqudtj6v1lpm4v4qjn3641s9fo1nl.apps.googleusercontent.com',
    iosBundleId: 'com.example.allycall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCEJgfSqSgDoxNlzu0hGhu2nBWmVWtviY',
    appId: '1:883016729268:web:e3a114025ab5b241d90de1',
    messagingSenderId: '883016729268',
    projectId: 'allycall',
    authDomain: 'allycall.firebaseapp.com',
    storageBucket: 'allycall.firebasestorage.app',
  );

}